sudo: required
services:
  - docker

before_install:
  - docker build -t danielhasler/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run danielhasler/react-test npm test -- --coverage

after_success:
  - docker build -t danielhasler/multi-client ./client
  - docker build -t danielhasler/multi-nginx ./nginx
  - docker build -t danielhasler/multi-server ./server
  - docker build -t danielhasler/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push danielhasler/multi-client
  - docker push danielhasler/multi-nginx
  - docker push danielhasler/multi-server
  - docker push danielhasler/multi-worker
  